// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djmzthmmgjlkfgwkawzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbXp0aG1tZ2psa2Znd2thd3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MTE5NTUsImV4cCI6MjA3NjQ4Nzk1NX0.Nm8JhNANHuPjiRWMbvxoDObc94k5l679KGOBUHYhfew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});